# Copyright 2017 Billy Holmes
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rhevm
  namespace: virt
spec:
  replicas: 1
  selector:
    app: rhevm
    ver: v1
    provides: rhevm
  template:
    metadata:
      name: rhevm
      labels:
        app: rhevm
        ver: v1
        provides: rhevm
    spec:
      containers:
      - name: httpd
        image: my-local-registry.example.com/rhel7/rhevm:4.0-0
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
          - name: TZ
            value: "America/New_York"
        args:
          - httpd
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        volumeMounts: []
      - name: engine
        image: my-local-registry.example.com/rhel7/rhevm:4.0-0
        resources:
          limits:
            cpu: 4000m
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 1Gi
        env:
          - name: TZ
            value: "America/New_York"
        args:
          - engine
        ports: []
        volumeMounts: []
      - name: engine-dwh
        image: my-local-registry.example.com/rhel7/rhevm:4.0-0
        resources:
          limits:
            cpu: 4000m
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 1Gi
        env:
          - name: TZ
            value: "America/New_York"
        args:
          - engine-dwh
        ports: []
        volumeMounts: []
      - name: websocket
        image: my-local-registry.example.com/rhel7/rhevm:4.0-0
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        env:
          - name: TZ
            value: "America/New_York"
        args:
          - websocket
        ports: []
        volumeMounts: []
      volumes: []
      nodeSelector: {}
